name: Use the Composite Action with Actions

on:
  push:
    branches: [ "main" ]

jobs:
  myJob:
    name: My Job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sewnguyenp2206
          password: Phu0005l5


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: sewnguyenp2206/video-service
